### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by miguelemosreverte** [Phalanstere/VisualTimebar#1]
Hi! I find your project absolutely valuable since its the exact thing i have been looking for. Absolutely fantastic.

Now the problem is that I just cannot run it. Hopefully it is because I do not have a ton of experience with npm or browserify. But most importantly, at the end of the day i am sure you are just going to find the issue really easy to solve since it works on your side, and you, being the developer, know exactly how you made it work.

**So lets get to the details:**

When trying the npm install way, it installs correctly, and after creating a folder called images and filling it with images, the command `node node_modules/cluster-painter/create_cluster.js` works, and creates the json file succesfully. Now comes the problem: when using the next command, having created the html and the index.js file, `browserify -t browserify-css index.js > bundle.js`, it returns this error message:

**Error: Cannot find module 'browserify-css'** from '/home/migue/Desktop/test'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

Okay, sure enough I do the following: I install browserify-css, right?
`npm install --save-dev browserify-css`

But that is still not enough, because then the following error message appears, when trying to browserify the project:

**Error: Cannot find module './lib/vis.min.js'** from '/home/migue/Desktop/test'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

Okay, then, I think. Maybe I will copy the lib folder from your other installation example, the one that runs right of the shelf. (It does not for me, I can show you the problems I had with that one, if you want me to)

And so next error is:

**Error: Cannot find module 'browserify-fs**' from '/home/migue/Desktop/test/node_modules/visual-timeline/lib'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

Anyway. Again, just like I tried really hard with the second way of installing the project, the first one did not work either, and I can show you in great detail the problems I had with that one, too.

The good thing is that I am sure you know exactly how to install it correctly, and that a few minutes of your time can help not only me, but a ton of the others npm illiterates out there who would enjoy your project if only there was a step by step tutorial that helped them avoid problems like the ones I am currently facing.

Cheers, and great job!

**Comment by miguelemosreverte** [comment]
About using the easier installation method, the first one:

First I run `npm install`, which works correctly.
Then I add the folder with the images, and run the `node node_modules/cluster-painter/create_cluster.js`
which works too, here is the output: 

```
you might want to add a callback
{ writeFile: [Function], init: [Function] }
success
sollte das File schreiben, dann den Callback aufrufen 8
Timeframe is week
cluster.json successfully stored!
```

That done, its time to make the bundle.js file needed by the html file.
The command `browserify -t browserify-css index.js > bundle.js` is run with no problems, and the bundle.js file is created.

Time to test the html!
![image](https://cloud.githubusercontent.com/assets/9152392/20248621/a11897b0-a9c6-11e6-9e69-22785e788563.png)
No timeline can be seen.

But because I am a hard worker I found a bundle.js file inside the lib folder! So I replaced the created one with the one that came with the downloaded repo, and this happened:
![image](https://cloud.githubusercontent.com/assets/9152392/20248636/f33f2e96-a9c6-11e6-87b2-d95444f7d858.png)

Sadly there are still no signs of the events on the timeline. The timeline is completely empty.

But hey, that's how far I got it to work.

**Comment by miguelemosreverte** [comment]
Extra proof in case the last screenshoot appears to not be zoomed back enought to show the completely empty timeline. The photos are the one posted on the demo, taken around November of 2015.

![image](https://cloud.githubusercontent.com/assets/9152392/20248668/9fcab748-a9c7-11e6-8178-b48af086563e.png)
